# Generated by Django 5.1.2 on 2024-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
